//****************************************************************************
// SMaLL, Software for Machine Learning Libraries
// Copyright 2023 by The SMaLL Contributors, All Rights Reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// For additional details (including references to third party source code and
// other files) see the LICENSE file or contact permission@sei.cmu.edu. See
// Contributors.txt for a full list of contributors. Created, in part, with
// funding and support from the U.S. Government (see Acknowledgments.txt file).
// DM23-0126
//****************************************************************************

#pragma once

#include "../arm/intrinsics.h"

#ifdef FLOAT_CONV_TILE_C
#undef FLOAT_CONV_TILE_C
#endif

#define FLOAT_CONV_TILE_C(step, I, W)                                   \
    if (_UNROLL == 1) {                                                 \
        /*float const *aa = I;*/                                        \
        float const *bb = W;                                            \
        float32x4_t a_0;                                                \
        float32x4_t a_1;                                                \
        float32x4_t a_2;                                                \
        float32x4_t a_3;                                                \
        float32x4_t a_4;                                                \
        float32x4_t a_5;                                                \
        float32x4_t b_0;                                                \
        float32x4_t b_1;                                                \
        float32x4_t b_2;                                                \
        float32x4_t b_3;                                                \
        a_0 = vld1q_dup_f32(I + 0 * step + 0 * FLOAT_SIMD);             \
        b_0 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_dup_f32(I + 1 * step + 0 * FLOAT_SIMD);             \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_dup_f32(I + 2 * step + 0 * FLOAT_SIMD);             \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_dup_f32(I + 3 * step + 0 * FLOAT_SIMD);             \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_dup_f32(I + 4 * step + 0 * FLOAT_SIMD);             \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_dup_f32(I + 5 * step + 0 * FLOAT_SIMD);             \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
    } else {                                                            \
        /*float const *aa = I;*/                                        \
        float const *bb = W;                                            \
        float32x4_t a_0;                                                \
        float32x4_t a_1;                                                \
        float32x4_t a_2;                                                \
        float32x4_t a_3;                                                \
        float32x4_t a_4;                                                \
        float32x4_t a_5;                                                \
        float32x4_t b_0;                                                \
        float32x4_t b_1;                                                \
        float32x4_t b_2;                                                \
        float32x4_t b_3;                                                \
        a_0 = vld1q_f32(I + 0 * step + 0 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 0 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 0 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 0 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 0 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        bb += 64;                                                       \
        a_0 = vld1q_f32(I + 0 * step + 1 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 1 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 1 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 1 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 1 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        bb += 64;                                                       \
        a_0 = vld1q_f32(I + 0 * step + 2 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 2 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 2 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 2 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 2 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        bb += 64;                                                       \
        a_0 = vld1q_f32(I + 0 * step + 3 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 0*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[0]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 3 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 1*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[1]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 3 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 2*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[2]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        a_0 = vld1q_f32(I + 0 * step + 3 * FLOAT_SIMD);                 \
        b_0 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 0)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_0) : "w"(b_0), "w"(a_0)); \
        b_1 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 1)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_1) : "w"(b_1), "w"(a_0)); \
        b_2 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 2)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_2) : "w"(b_2), "w"(a_0)); \
        b_3 = vld1q_f32(bb + 3*FLOAT_C_ob + (0 * 4 + 3)*FLOAT_SIMD);    \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_0_3) : "w"(b_3), "w"(a_0)); \
        a_1 = vld1q_f32(I + 1 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_0) : "w"(b_0), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_1) : "w"(b_1), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_2) : "w"(b_2), "w"(a_1)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_1_3) : "w"(b_3), "w"(a_1)); \
        a_2 = vld1q_f32(I + 2 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_0) : "w"(b_0), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_1) : "w"(b_1), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_2) : "w"(b_2), "w"(a_2)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_2_3) : "w"(b_3), "w"(a_2)); \
        a_3 = vld1q_f32(I + 3 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_0) : "w"(b_0), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_1) : "w"(b_1), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_2) : "w"(b_2), "w"(a_3)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_3_3) : "w"(b_3), "w"(a_3)); \
        a_4 = vld1q_f32(I + 4 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_0) : "w"(b_0), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_1) : "w"(b_1), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_2) : "w"(b_2), "w"(a_4)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_4_3) : "w"(b_3), "w"(a_4)); \
        a_5 = vld1q_f32(I + 5 * step + 3 * FLOAT_SIMD);                 \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_0) : "w"(b_0), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_1) : "w"(b_1), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_2) : "w"(b_2), "w"(a_5)); \
        __asm__ volatile ("fmla %0.4s, %1.4s, %2.s[3]" : "+w"(c_5_3) : "w"(b_3), "w"(a_5)); \
        bb += 64;                                                       \
    }
