name: Test ARM Build

on: [push]

#env:
#  ACTIONS_RUNNER_DEBUG: true

jobs:
  build-and-test:

    # The host should always be Linux
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            mkdir ${{github.workspace}}/build
            cd ${{github.workspace}}/build
            cmake ${{github.workspace}} -DCMAKE_UARCH=REF 
            cmake --build . -j
            ctest --rerun-failed --output-on-failure