name: Test Zen2 Build

on: [push, pull_request]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cmake -B ${{github.workspace}}/build -DCMAKE_UARCH=ZEN2 
      - run: cmake --build ${{github.workspace}}/build -j
      - run: cd ${{github.workspace}}/build
      - run: make test

    
      
  
  