name: Test Reference Build

on: [push, pull_request]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: mkdir ${{github.workspace}}/build
      - run: cd ${{github.workspace}}/build
      - run: cmake ${{github.workspace}} -DCMAKE_UARCH=REF 
      - run: cmake --build . -j
      - run: make test

    
      
  
  